/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    id("org.graalvm.buildtools.native") version "0.10.6"
    id("buildlogic.java-application-conventions")
}


dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("info.picocli:picocli:4.7.7")
    implementation("org.jmdns:jmdns:3.6.3")
    implementation("org.slf4j:slf4j-nop:2.0.9")
    implementation("com.google.code.gson:gson:2.13.2")
    annotationProcessor("info.picocli:picocli-codegen:4.7.7")

}


tasks.named<JavaCompile>("compileJava") {
    options.compilerArgs.add("-Aproject=${project.group}/${project.name}")
}

tasks.named<JavaExec>("run") {
  standardInput = System.`in`
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}


