/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import picocli.CommandLine;

import org.example.app.cli.lansync;

public class App {
  public static void main(String[] args) {

    int exitcode = new CommandLine(new lansync()).execute(args);
    System.exit(exitcode);
  }
}
